2025-07-06 18:42:56,848 [main.py         | 48] INFO: Start to run instance_1
2025-07-06 18:42:56,849 [simulate_api.py | 60] INFO: Start time of the simulator: 2025-07-06 00:00:00, time interval:  600.00
2025-07-06 18:42:56,866 [input_utils.py  | 48] INFO: Get 154 factories
2025-07-06 18:42:57,695 [input_utils.py  | 52] INFO: Get 23562 routes
2025-07-06 18:42:57,714 [input_utils.py  | 57] INFO: Get 5 vehicles
2025-07-06 18:42:57,734 [input_utils.py  | 61] INFO: Get 50 orders
2025-07-06 18:42:57,734 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2025-07-06 18:42:57,734 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2025-07-06 18:42:57,734 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2025-07-06 18:42:57,734 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2025-07-06 18:42:57,734 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2025-07-06 18:42:57,734 [simulate_environment.py | 99] INFO: **************************************************
2025-07-06 18:42:57,734 [simulate_environment.py | 103] INFO: cur time: 2025-07-06 00:10:00, pre time: 2025-07-06 00:00:00
2025-07-06 18:42:57,734 [simulate_environment.py | 140] INFO: Start to update the input of 2025-07-06 00:10:00
2025-07-06 18:42:57,734 [simulate_environment.py | 167] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2025-07-06 18:42:59,039 [simulate_environment.py | 232] INFO: 
2025-07-06 18:42:58,973 [main_algorithm.py | 31] ERROR: Failed to run algorithm
2025-07-06 18:42:58,973 [main_algorithm.py | 32] ERROR: Error: cost_of_a_route() takes 5 positional arguments but 6 were given, Traceback (most recent call last):
  File "C:\PHUC\DPDP\New_DPDP\main_algorithm.py", line 28, in <module>
    main()
  File "C:\PHUC\DPDP\New_DPDP\algorithm\main.py", line 33, in main
    dispatch_new_orders(vehicleid_to_plan , id_to_factory , route_map , id_to_vehicle , id_to_unlocated_items , new_order_itemIDs)
  File "C:\PHUC\DPDP\New_DPDP\algorithm\engine.py", line 448, in dispatch_new_orders
    isExhausive , bestInsertVehicleID, bestInsertPosI, bestInsertPosJ , bestNodeList = dispatch_nodePair(node_list , id_to_vehicle , vehicleid_to_plan , route_map)
                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PHUC\DPDP\New_DPDP\algorithm\engine.py", line 563, in dispatch_nodePair
    tmp_cost = cost_of_a_route(exhaustive_route_node_list , vehicle , id_to_vehicle , route_map , vehicleid_to_plan , mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cost_of_a_route() takes 5 positional arguments but 6 were given

FAIL

2025-07-06 18:42:59,039 [simulate_environment.py | 246] ERROR: 
2025-07-06 18:42:58,973 [main_algorithm.py | 31] ERROR: Failed to run algorithm
2025-07-06 18:42:58,973 [main_algorithm.py | 32] ERROR: Error: cost_of_a_route() takes 5 positional arguments but 6 were given, Traceback (most recent call last):
  File "C:\PHUC\DPDP\New_DPDP\main_algorithm.py", line 28, in <module>
    main()
  File "C:\PHUC\DPDP\New_DPDP\algorithm\main.py", line 33, in main
    dispatch_new_orders(vehicleid_to_plan , id_to_factory , route_map , id_to_vehicle , id_to_unlocated_items , new_order_itemIDs)
  File "C:\PHUC\DPDP\New_DPDP\algorithm\engine.py", line 448, in dispatch_new_orders
    isExhausive , bestInsertVehicleID, bestInsertPosI, bestInsertPosJ , bestNodeList = dispatch_nodePair(node_list , id_to_vehicle , vehicleid_to_plan , route_map)
                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PHUC\DPDP\New_DPDP\algorithm\engine.py", line 563, in dispatch_nodePair
    tmp_cost = cost_of_a_route(exhaustive_route_node_list , vehicle , id_to_vehicle , route_map , vehicleid_to_plan , mode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cost_of_a_route() takes 5 positional arguments but 6 were given

FAIL

2025-07-06 18:42:59,039 [simulate_environment.py | 247] ERROR: Can not catch the 'SUCCESS' from the algorithm. 未寻获算法输出成功标识'SUCCESS'。
